print("Назовите по порядку этапы развития человека")
print("Первый этап?")
a1 = input()
print("Второй этап?")
a2 = input()
print("Третий этап?")
a3 = input()
print("Четвертый этап?")
a4 = input()
print("Пятый этап?")
a5 = input()
print("Шестой этап?")
a6 = input()
print("Седьмой этап?")
a7 = input()
print("Ваши ответы:", a1, a2, a3, a4, a5, a6, a7, sep=("=>"))